# All possible configuration.
# For more see: http://jekyllrb.com/docs/configuration/
destination: ./_site
lsi:         false
port:        4000
highligher:  true

# Build settings
markdown: kramdown

highlighter: rouge

kramdown:
  extensions: [smart]

# This is the default base url path.
BASE_PATH : http://Camouflage129.github.io/

# Website title.
title : Camouflage

dispus-shortname : Camouflage129

# label listing. [create labels for category in folder `_label`]
collections:
  - category
  - samsung
  - baekjoon

# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title

# Pagination based on number of posts
# For more see: http://jekyllrb.com/docs/pagination/
#paginate: 20
#paginate_path: "page/:num"

  ## Author Details ##
###########################
author:
# Info
  name: Camouflage
  role: Computer Programmer
  email: hyunho129@naver.com
  image: images/Camouflage.jpg

#  About
  about: Camouflage Blog
# copyright
  copyright: "Some rights reserved &#169; 2015 Ankan Biswas."

# Disable custom plugins,and ignore symbolic links..
# For more see: http://jekyllrb.com/docs/configuration/
safe:    false
# Jekyll-sitemap auto generate
# For more see: https://github.com/jekyll/jekyll-sitemap
gems:
  - jekyll-sitemap
